import { CruiseType } from "./Cruise";

export const januaryCruiseApi: CruiseType[] = [
  {
    id: 1,
    name: "Portuguese Island",
    ship: "MSC Musica",
    nights: "4 Nights, 5 Days",
    date: "02 Jan 2025",
    description: "Durban - Portuguese Island - Pomene",
    image: "/images/cruises/msc-hero.jpg",
    price: 1000,
    cruiseItenerary: [
      {
        day: "Day 1",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 2",
        date: "02 Jan 2025",
        location: "Portuguese Island",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 3",
        date: "02 Jan 2025",
        location: "Pomene",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 4",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
    ],
  },
  {
    id: 2,
    name: "Pomene",
    ship: "MSC Musica",
    nights: "4 Nights, 5 Days",
    date: "02 Jan 2025",
    description: "Durban - Portuguese Island - Pomene",
    image: "/images/cruises/msc-hero.jpg",
    price: 1000,
    cruiseItenerary: [
      {
        day: "Day 1",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 2",
        date: "02 Jan 2025",
        location: "Portuguese Island",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 3",
        date: "02 Jan 2025",
        location: "Pomene",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 4",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
    ],
  },
  {
    id: 3,
    name: "Durban2Nowhere",
    ship: "MSC Musica",
    nights: "4 Nights, 5 Days",
    date: "02 Jan 2025",
    description: "Durban - Portuguese Island - Pomene",
    image: "/images/cruises/msc-hero.jpg",
    price: 1000,
    cruiseItenerary: [
      {
        day: "Day 1",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 2",
        date: "02 Jan 2025",
        location: "Portuguese Island",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 3",
        date: "02 Jan 2025",
        location: "Pomene",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 4",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
    ],
  },
  {
    id: 4,
    name: "Namibia",
    ship: "MSC Musica",
    nights: "4 Nights, 5 Days",
    date: "02 Jan 2025",
    description: "Durban - Portuguese Island - Pomene",
    image: "/images/cruises/msc-hero.jpg",
    price: 1000,
    cruiseItenerary: [
      {
        day: "Day 1",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 2",
        date: "02 Jan 2025",
        location: "Portuguese Island",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 3",
        date: "02 Jan 2025",
        location: "Pomene",
        arrive: "10:00",
        depart: "11:00",
      },
      {
        day: "Day 4",
        date: "02 Jan 2025",
        location: "Durban",
        arrive: "10:00",
        depart: "11:00",
      },
    ],
  },
];
